---
name: Games-Sudoku-General
version: 0.009
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Solve Sudoku and related puzzles
license: perl
resources:
  license: http://dev.perl.org/licenses/
dynamic_config: 1
provides:
  Games::Sudoku::General:
    file: lib/Games/Sudoku/General.pm
    version: 0.009
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
