---
abstract: 'Solve Sudoku and related puzzles'
author:
  - 'Tom Wyant (wyant at cpan dot org)'
build_requires:
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Sudoku-General
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Games::Sudoku::General:
    file: lib/Games/Sudoku/General.pm
    version: 0.013
requires:
  Carp: 0
  constant: 0
  perl: 5.006002
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Games-Sudoku-General
  license: http://dev.perl.org/licenses/
version: 0.013
